[package]
name = "p-vector"
version = "0.1.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"

[dependencies]
# logging facilities
log = "0.4"
env_logger = "0.9"
# scanning facilities
walkdir = "2.3"
ar = "0.8"
tar = "0.4"
xz2 = "0.1"
flate2 = "1.0"
# utilities
anyhow = "1.0"
sha2 = "0.9"
rayon = "1.5"
sailfish = "0.3"
faster-hex = "0.6"
crossbeam-queue = "0.3"
tempfile = "3.2"
time = { version = "0.2", default-features = false }
sequoia-openpgp = { version = "1.3", features = ["crypto-nettle"], default-features = false }
# parser implementations
nom = "^6"
toml = "0.5"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
goblin = "0.4"
# cli
argh = "0.1"
# async and database
tokio = { version = "^1", features = ["rt", "rt-multi-thread", "time", "macros", "fs"] }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "macros", "postgres", "chrono", "migrate", "json"] }
futures = "0.3"
async-compression = { version = "0.3", features = ["tokio", "gzip", "xz"] }
reqwest = "0.11"
