[config]
# PostgreSQL connection string
db_pgconn = "postgresql://localhost/packages"
# Use for package change notifier, set to null to disable it
# If you don't use this feature, disabling it could improve performance
change_notifier = "redis://127.0.0.1/"
# Path to repository
path = "/mirror/debs"
# Auto-discover branches
discover = true
# Brand name
origin = "AOSC"
# Force-refresh interval (in days)
ttl = 14
# Label name
label = "AOSC OS"
# Code name
codename = "Hotfix"
# Signing private key file (the certificate must include a signing (sub-)key)
# If your secret key is not a file (because it is on a smartcard or hardware token):
# Please export its public key using `gpg` and uncomment then edit the line below
# certificate = "gpg:///etc/p-vector/sign.pubkey"
certificate = "/etc/p-vector/sign.key"
# Enable abbs data sync (AOSC-specific, also deprecated)
abbs_sync = false
# Include extra files in the `dist` folder
# This can be useful if you run other add-on services using an APT repository
# extra_dist_files = "/var/cache/p-vector/extra-dists/"

# Enable acquire by hash mechanism. To disable, set this value to 0.
# To allow keeping unlimited number of Package file, set this value to -1.
acquire_by_hash = 5

[[branch]]
# Branch name
name = "stable"
# Branch description
desc = "AOSC OS Repository - Stable"

[[branch]]
name = "testing"
desc = "AOSC OS Repository - Testing"
# Branch-specific force-refresh interval (7 days)
ttl = 7
