[config]
# PostgreSQL connection string
db_pgconn = "postgresql://localhost/packages"
# Use for package change notifier, set to null to disable it
# If you don't use this feature, disabling it could improve performance
change_notifier = "ipc:///tmp/p-vector-changes"
# Path to repository
path = "/mirror/debs"
# Auto-discover branches
discover = true
# Brand name
origin = "AOSC"
# Force-refresh interval (in days)
ttl = 14
# Label name
label = "AOSC OS"
# Code name
codename = "Hotfix"
# Signing private key file (the certificate must include a signing (sub-)key)
# If your secret key is not a file (because it is on a smartcard or hardware token):
# Please export its public key using `gpg` and uncomment then edit the line below
# certificate = "gpg:///etc/p-vector/sign.pubkey"
certificate = "/etc/p-vector/sign.key"
# Delay between each QA (analyze) run (in hours)
# set this value to 0 to run QA each time; set to -1 to disable QA function altogether
qa_interval = 4
# Enable abbs data sync (AOSC-specific, if you are running a private repository, you should disable this)
abbs_sync = true

[[branch]]
# Branch name
name = "stable"
# Branch description
desc = "AOSC OS Repository - Stable"

[[branch]]
name = "testing"
desc = "AOSC OS Repository - Testing"
# Branch-specific force-refresh interval (7 days)
ttl = 7
