-- delete all the tables
DROP TABLE IF EXISTS trees CASCADE;
DROP TABLE IF EXISTS tree_branches CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS package_duplicate CASCADE;
DROP TABLE IF EXISTS package_versions CASCADE;
DROP TABLE IF EXISTS package_spec CASCADE;
DROP TABLE IF EXISTS package_dependencies CASCADE;
DROP TABLE IF EXISTS dpkg_repo_stats CASCADE;
DROP TABLE IF EXISTS upstream_status CASCADE;
DROP TABLE IF EXISTS package_upstream CASCADE;
DROP TABLE IF EXISTS anitya_link CASCADE;
DROP TABLE IF EXISTS anitya_projects CASCADE;
DROP TABLE IF EXISTS repo_marks CASCADE;
DROP TABLE IF EXISTS repo_committers CASCADE;
DROP TABLE IF EXISTS repo_package_rel CASCADE;
DROP TABLE IF EXISTS repo_package_basherr CASCADE;
DROP TABLE IF EXISTS repo_branches CASCADE;
