TABLES = (
    ("abbs.db", (
        "trees", "tree_branches", "packages", "package_duplicate",
        "package_versions", "package_spec", "package_dependencies",
        "dpkg_repo_stats"
    )),
    # ("piss.db", (
    #     "upstream_status", "package_upstream", "anitya_link", "anitya_projects"
    # )),
)
SRCREPOS = ("aosc-os-abbs",)
MARKS_TABLES = (
    "marks", "committers", "package_rel", "package_basherr", "branches")
MARKS_DB_SFX = "-marks.db"

print("""-- Automatically generated by gen_pvsync.py
DROP SCHEMA IF EXISTS abbs CASCADE;
CREATE SCHEMA abbs;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server INTO abbs;
""")
for db, tables in TABLES:
    schema_name = db.split(".")[0]
    for table in tables:
        print(f'TRUNCATE "{table}";\nINSERT INTO "{table}" SELECT * FROM {schema_name}."{table}";\n')
