-- Automatically generated by gen_pvsync.py
DROP SCHEMA IF EXISTS abbs CASCADE;
CREATE SCHEMA abbs;
IMPORT FOREIGN SCHEMA public FROM SERVER sqlite_server INTO abbs;

TRUNCATE "trees";
INSERT INTO "trees" SELECT * FROM abbs."trees";

TRUNCATE "tree_branches";
INSERT INTO "tree_branches" SELECT * FROM abbs."tree_branches";

TRUNCATE "packages";
INSERT INTO "packages" SELECT * FROM abbs."packages";

TRUNCATE "package_duplicate";
INSERT INTO "package_duplicate" SELECT * FROM abbs."package_duplicate";

TRUNCATE "package_versions";
INSERT INTO "package_versions" SELECT * FROM abbs."package_versions";

TRUNCATE "package_spec";
INSERT INTO "package_spec" SELECT * FROM abbs."package_spec";

TRUNCATE "package_dependencies";
INSERT INTO "package_dependencies" SELECT * FROM abbs."package_dependencies";

TRUNCATE "dpkg_repo_stats";
INSERT INTO "dpkg_repo_stats" SELECT * FROM abbs."dpkg_repo_stats";
